version: "2.2"
services:
  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - ./docker/mongodb/logs/:/var/logs/mongodb/:delegated
        - mongodata:/data/db
volumes:
  mongodata:
    driver: local